### PR TITLE
Fix ProgressHandler conflicts with datetime imports

### LINKED ISSUE #1618: [BUG] Cannot run any code or cell after importing * from datetime - Databricks Connect 15.4.7
**Describe the bug**
After upgrading cluster runtime to 15.4 LTS and then upgrading the Databricks Connect package to 15.4.7 using the VSCode extension, cells can no longer be run at all it seems. Every cell gives the error:

`AttributeError: 'ProgressHandler' object has no attribute 'p'`

Update:
The error message given is at the end of the stack trace.

The issue seems to occur when  you import datetime using `from datetime import *`. If this is removed then the notebook works!

**To Reproduce**

1. Use Databricks Copnnect 15.4.7
2. Run any cell that attempts to run on the cluster after running `from datetime import *`
```
from datetime import *
df = spark.read.table("samples.nyctaxi.trips")
df.show(5)
```

Image

The spark table read fails after importing * from datetime
Image

Image

### PR DESCRIPTION
**Pull request by ilia-db**
## Changes

Fixes #1618

## Tests

Manually

### CODE REVIEW

**Comment by ilia-db** [comment]
> do we have similar problems with other imports?

Technically all our top level imports can be overriden by the user code, I'll follow up on this PR and move the imports inside the functions, or use `as` with a more unique name on the top level.
