### ISSUE TITLE
[BUG] Cannot run any code or cell after importing * from datetime - Databricks Connect 15.4.7

### ISSUE THREAD

**Issue by Rooth123** [databricks/databricks-vscode#1618]
**Describe the bug**
After upgrading cluster runtime to 15.4 LTS and then upgrading the Databricks Connect package to 15.4.7 using the VSCode extension, cells can no longer be run at all it seems. Every cell gives the error:

`AttributeError: 'ProgressHandler' object has no attribute 'p'`

Update:
The error message given is at the end of the stack trace.

The issue seems to occur when  you import datetime using `from datetime import *`. If this is removed then the notebook works!

**To Reproduce**

1. Use Databricks Copnnect 15.4.7
2. Run any cell that attempts to run on the cluster after running `from datetime import *`
```
from datetime import *
df = spark.read.table("samples.nyctaxi.trips")
df.show(5)
```

![Image](https://github.com/user-attachments/assets/01c8c92d-0af1-4664-a0be-34d8383149b8)

The spark table read fails after importing * from datetime
![Image](https://github.com/user-attachments/assets/757f2b74-6939-431e-b721-c42f443ae053)

![Image](https://github.com/user-attachments/assets/7e2c1a96-e1df-4b36-9cbf-10ae40c91180)

**Comment by ilia-db** [comment]
Thanks for the report! To unblock yourself while we're working on a fix you can disable the progress in the settings: 

<img width="636" alt="Image" src="https://github.com/user-attachments/assets/aaa5c27e-2f1c-4a4f-bba8-c79f72620cd2" />
