### PR TITLE
Upgrade @vscode/test-electron 2.3.8 → 3.0.0 (with TypeScript 5.9.3)

### PR DESCRIPTION
**Pull request by rugpanov**
## Why

Dependabot #1974 bumped `@vscode/test-electron` to 3.0.0 but the one-line `package.json` change **breaks the build**. test-electron 3 ships a `.d.ts` (`out/util.d.ts`) that uses the generic `Buffer<ArrayBufferLike>` type, which `@types/node@22` only exposes to **TypeScript >= 5.7** (its `typesVersions` maps TS <=5.6 to a non-generic `Buffer` variant). The repo was pinned to `typescript@^5.3.3`, so tsc reported:

```
error TS2315: Type 'Buffer' is not generic.
```

The bump also left `yarn.lock` out of sync.

Rather than mask the mismatch with a repo-wide `skipLibCheck` (which would stop type-checking **all** `.d.ts` files and could hide real dependency type errors), this fixes the **root cause** by raising TypeScript to a version that type-checks test-electron 3's declarations natively.

## What

- Bump `@vscode/test-electron` `^2.3.8` → `^3.0.0`.
- Bump `typescript` `^5.3.3` → `^5.9.3` (>=5.7 for the generic `Buffer`; stays <6.1.0 so `@typescript-eslint@8`'s peer range and `ts-node@10` remain satisfied — TS 6.0 breaks both, tracked separately in #1975).
- Regenerate `yarn.lock` (also dedupes the previously-split direct `2.3.8` / transitive `2.5.2` test-electron resolutions onto `3.0.0`).

Test-only devtooling — no product/user-facing change. test-electron 3's only declared behavioural change over v2 is requiring Node >=22, which the extension already mandates (`engines.node >=22.0`) and CI runs on.

## Verification

- `yarn install --immutable` passes (no `YN0028`, no `YN0060`).
- `yarn run build` (`tsc --build`) succeeds with **0 errors** under TS 5.9.3 — the generic-Buffer error is resolved natively, no `skipLibCheck`.
- `eslint src --ext ts` clean (typescript-eslint@8 handles TS 5.9).
- `ts-mocha --type-check` of the `sdk-extensions` integ suite type-checks.
- `yarn run test:unit`: **268 passing, 0 failing**. (The pre-existing `ClusterLoader` unhandled-rejection console noise is unrelated and also present on main.)

Supersedes #1974.

This pull request and its description were written by Isaac.

---

_This PR was created with [GitHub MCP](http://go/mcps)._

### CODE REVIEW

**Comment by rugpanov** [comment]
🤖 Integration tests ❌ **6 of 35 test jobs failed** for `d1eb3336` (29 passed).
[View run](https://github.com/databricks-eng/eng-dev-ecosystem/actions/runs/28863308276)

**Review by misha-db — APPROVED** [review]
